spring:
  application:
    name: store
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
        format_sql: true
    open-in-view: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true